language: php

php:
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - phpunit
